#!/bin/bash

source functions

function tryThis() {
 counter=1
  for i in $@; do
    if [ $counter -gt 1 ]; then
     echo $i
    fi
    counter=$((counter+1))
 done
}

writeTableHeaders outputFilename "Node Name" "IP Address" "report date" "os version"
