#!/bin/bash
#change root_path based on where scripts are located
ROOT_PATH=/var/www/html/audit


SCRIPTS=$ROOT_PATH/scripts
HTMLDIR=$ROOT_PATH/html
TEMPDIR=$SCRIPTS/temp
CONFDIR=$ROOT_PATH/conf
GeneratedScripts=$SCRIPTS/generated_scripts
HTMLMenu=$HTMLDIR/menu
DATADir=$HTMLDIR/data

DefaultUser="jeremiahj"
DefaultGroup="cwsrepo"
REMOTEUSER="cwsrepo"

