#!/bin/bash
source common/vars


function removeFiles() {
        isEmpty=`find $1 -type f -exec echo Found file {} \;`
        if [ "$isEmpty" != "" ]; then
                rm $1/* -rf
        fi
} #end removeFiles



#This script will remove all data generated by this application

removeFiles $TEMPDIR
removeFiles $GeneratedScripts
removeFiles $HTMLMenu
removeFiles $DATADir
